services:
  electro-discovery-service:
    build: ./discovery-service
    container_name: electro-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 5s
      retries: 4
  electro-config-service:
    build: ./config-service
    container_name: electro-config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 5s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://electro-discovery-service:8761/eureka
    depends_on:
      electro-discovery-service:
        condition: service_healthy
  electro-client-service:
    build: ./client-service
    container_name: electro-client-service
    ports:
      - '8083:8083'
    expose:
      - '8083'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 5s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://electro-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://electro-config-service:9999
    depends_on:
      electro-config-service:
        condition: service_healthy
  electro-product-service:
    build: ./product-service
    container_name: electro-product-service
    ports:
      - '8084:8084'
    expose:
      - '8084'
    environment:
      - DISCOVERY_SERVICE_URL=http://electro-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://electro-config-service:9999
    depends_on:
      electro-client-service:
        condition: service_healthy
  electro-gateway-service:
    build: ./gateway-service
    container_name: electro-gateway-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      - DISCOVERY_SERVICE_URL=http://electro-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://electro-config-service:9999
    depends_on:
      electro-config-service:
        condition: service_healthy
  front-electro-app:
    build: ./electro-app-front
    container_name: electro-app-front
    ports:
      - '80:80'
    expose:
      - '80'